### ISSUE TITLE
Formatting issue when running on macOS 

### ISSUE THREAD

**Issue by logicito** [zacharee/HINTControl#64]
With the latest beta 1.12.0 (TestFlight) while running on my MacBook there is a formatting issue with the LTE band, being narrower than the 5G band, and the actual band goes to the second line, I don't know if TestFlight is only for iOS and I should be using it? And go back to the macOS version from the Mac App Store? Thank you

<img width="479" alt="image" src="https://github.com/user-attachments/assets/001e2377-6320-4662-bb20-7381b22d572b">

**Comment by logicito** [comment]
This is with the Mac App Store version 1.10.5

<img width="476" alt="image" src="https://github.com/user-attachments/assets/982505a1-0677-41d7-91a2-c47caab5a42d">

**Comment by zacharee** [comment]
LTE data is flowing to the next line because the LTE RSRP is 4 characters while the 5G RSRP is only 3. There is a bug, though, which is that the data is in the wrong order now. That should be fixed in the next version, and will also make formatting more consistent, since the NBID will be last instead of in the middle.

**Comment by logicito** [comment]
Thank you, but it's a bug only on macOS, because on iOS and iPadOS looks ok

**Comment by zacharee** [comment]
The formatting depends on a lot of things, including screen size, element scaling, and font scaling. The information is set to automatically go to another row if it runs out of room.

**Comment by logicito** [comment]
I think it’s a macOS bug then, because I run it in full scree on macOS
